name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') || github.sha }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with skip tests
        run: mvn -B package --file pom.xml -DskipTests
        
      - name: Run Docker-Compose Test
        uses: hoverkraft-tech/compose-action@v2.3.0
        with:
          compose-file: "./docker-compose-test.yml"

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Chown Data Folder
        run: sudo chown -R $USER:$USER ./data

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=KimleangSama_Bulk-Payment-System
